# Generated by Django 4.0.4 on 2022-05-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auther', models.CharField(max_length=100, verbose_name='主机管理员')),
                ('hostip', models.GenericIPAddressField(verbose_name='主机地址')),
                ('Email', models.EmailField(max_length=254, verbose_name='邮件地址')),
                ('Active', models.IntegerField(choices=[(2, '失效'), (1, '存活')], default=1, verbose_name='存活状态')),
                ('record_time', models.CharField(max_length=100, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='Kafka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kafka', models.CharField(max_length=100, verbose_name='Kafka地址')),
                ('Active', models.IntegerField(choices=[(1, '存活'), (2, '失效')], default=1, verbose_name='是否存活')),
            ],
            options={
                'verbose_name': 'Kakfa地址',
                'verbose_name_plural': 'Kakfa地址',
            },
        ),
    ]
